---
global:
    data:
        domain: gca.co.ao
        snmp:
          ip: ["10.30.99.241"]
          local: "DATACENTER GCA CO AO"
          contact: "support.helpdesk@bihangoal.net"
          pub: "gca_pub"
          wr: "gca_wr"

        kron:
          name: "AUTO_BKP_CFG"

        ftp:
          ip: 10.30.23.1
          username: ciscoBKP
          password: ciscoBKP

        ntp:
          ip:
            - 10.30.99.254
          
        dns_server:
            ip:
                - 10.110.0.1
                - 10.110.0.2
        tacacs:
            method: "use-srvtacacs"
            ip: ["10.30.10.10"]
            key: "s3cr3t2016"
            timeout: 5

        loggin:
            ip: 
                - 10.30.99.251
                - 10.30.99.244
            traplevel: 7
            severity: 7
            size: 100000
            monlevel: 7
            consolevel: 7



distribution-switch:
    data:
        type: "Switch"
core-switch:
    data:
        vlans:
            - {name: VMW_VLAN_PROV2, tag: "801"}
            - {name: VMW_VLAN_ILO_NEW, tag: "802"}
            - {name: VMW_VLAN_VMWARE_NEW, tag: "803"}
            - {name: VMW_VLAN_STORAGE_NEW, tag: "804"}
            - {name: VMW_VLAN_V_VMOTION, tag: "805"}
            - {name: VMW_VLAN_FAULT_TOLERANCE, tag: "806"}
            - {name: VMW_VLAN_VXLAN, tag: "807"}
            - {name: VMW_VLAN_LINK_VIRTUAL_TO_FISIC, tag: "808"}
            - {name: VMW_VLAN_VCENTER_HA, tag: "809"}
        vtp:
            mode: "transparent"

        multicast:
            anycast:
                intf_name: "Loopback 10"
                description: "ANYCAST RENDEZ VOUS"
                ip: 12.12.12.12
                subnet: 255.255.255.255
            peer_victoria: 10.104.63.254
            peer_cuca: 10.104.127.254
            
        
            
test-device:
    data:
        type: "lab"
edge-security-gateway:
    data:
        type: "vmware-nsx"
nsx-controller:
    data:
        type: "vmware-nsx"
nsx-management:
    data:
        type: "vmware-nsx"
universal-dlr:
    data:
        type: "vmware-nsx"

...