---
CSR1000v-lab:
  data:
    device_name: CSR1000v-lab
    interfaces:
    - description: Management
      ip: 10.30.107.246
      mgt_only: true
      name: GigabitEthernet1
      subnet: 255.255.255.0
    model: CSRV1000v
    role: test-device
    site: VICTORIA
  groups:
  - test-device
  - global
  hostname: 10.30.107.246
  password: admin2019
  platform: ios
  username: admin
CoreFABRcuca01:
  data:
    device_name: CoreFABRcuca01
    interfaces:
    - description: Link Upstream 01 SPINE CUCA
      ip: 172.16.127.1
      mgt_only: false
      name: GigabitEthernet5/3
      peer_connected:
        peer: CoreSPINEcuca01
        peer_intf: GigabitEthernet3/48
      status: Connected
      subnet: 255.255.255.254
    - description: RID Cuca Distribution
      ip: 10.104.127.2
      mgt_only: false
      name: Loopback0
      subnet: 255.255.255.255
    model: C4500
    role: distribution-switch
    site: CUCA
  groups:
  - distribution-switch
  - global
  hostname: 10.104.127.2
  password: admin2019
  platform: ios
  username: admin
CoreSPINEcuca01:
  data:
    device_name: CoreSPINEcuca01
    interfaces:
    - description: Link Downstream 01 FABR CUCA
      ip: 172.16.127.0
      mgt_only: false
      name: GigabitEthernet3/48
      peer_connected:
        peer: CoreFABRcuca01
        peer_intf: GigabitEthernet5/3
      status: Connected
      subnet: 255.255.255.254
    - description: RID Cuca Spine
      ip: 10.104.127.2
      mgt_only: false
      name: Loopback0
      subnet: 255.255.255.255
    - description: RendezVous MultiCast
      ip: 10.104.127.254
      mgt_only: false
      name: Loopback1
      subnet: 255.255.255.255
    - description: VMW_PROV
      ip: 10.104.0.254
      mgt_only: false
      name: VL801
      subnet: 255.255.255.0
      tag: '801'
    - description: VL_HP_ILO
      ip: 10.104.1.254
      mgt_only: false
      name: VL802
      subnet: 255.255.255.0
      tag: '802'
    - description: NSXMGT
      ip: 10.104.2.254
      mgt_only: false
      name: VL803
      subnet: 255.255.255.0
      tag: '803'
    - description: VMW_STORAGE
      ip: 10.104.3.30
      mgt_only: false
      name: VL804
      subnet: 255.255.255.224
      tag: '804'
    - description: VMW_VMOTION
      ip: 10.104.3.62
      mgt_only: false
      name: VL805
      subnet: 255.255.255.224
      tag: '805'
    - description: VMW_FAULT_TOLERANCE
      ip: 10.104.3.94
      mgt_only: false
      name: VL806
      subnet: 255.255.255.224
      tag: '806'
    - description: VMW_VXLAN_VTEP
      ip: 10.104.3.126
      mgt_only: false
      name: VL807
      subnet: 255.255.255.224
    - description: Link Downstream 01 ESG CUCA
      ip: 172.16.10.10
      mgt_only: false
      name: VL808
      peer_connected:
        peer: dcgca.esg.border
        peer_intf: vif.uplink2cuca
      status: Connected
      subnet: 255.255.255.252
      tag: '808'
    - description: VMW_VCENTER_HA
      ip: 10.104.3.129
      mgt_only: false
      name: VL809
      subnet: 255.255.255.248
      tag: '809'
    model: C6500
    role: core-switch
    site: CUCA
  groups:
  - core-switch
  - global
  hostname: 10.104.127.1
  password: admin2019
  platform: ios
  username: admin
CoreSPINEvictoria01:
  data:
    device_name: CoreSPINEvictoria01
    interfaces:
    - description: RID Victoria Spine
      ip: 10.104.127.2
      mgt_only: false
      name: Loopback0
      subnet: 255.255.255.255
    - description: RendezVous MultiCast Victoria
      ip: 10.104.127.254
      mgt_only: false
      name: Loopback1
      subnet: 255.255.255.255
    model: C6500
    role: core-switch
    site: VICTORIA
  groups:
  - core-switch
  - global
  hostname: 10.104.63.1
  password: admin2019
  platform: ios
  username: admin
dcgca.dhcp.server:
  data:
    device_name: dcgca.dhcp.server
    interfaces:
    - description: ''
      ip: 10.110.1.254
      mgt_only: false
      name: vif.gca.application
      subnet: 255.255.255.0
    - description: ''
      ip: 10.110.7.254
      mgt_only: false
      name: vif.gca.desktop
      subnet: 255.255.252.0
    - description: ''
      ip: 10.110.3.254
      mgt_only: false
      name: vif.gca.stage
      subnet: 255.255.255.128
    model: NSX-ESG
    role: edge-security-gateway
    site: CUCA
  groups:
  - edge-security-gateway
  - global
  hostname: 10.110.1.253
  password: admin2019
  platform: ios
  username: admin
dcgca.esg.border:
  data:
    device_name: dcgca.esg.border
    interfaces:
    - description: ''
      ip: 172.16.10.2
      mgt_only: false
      name: vif.cuc.core2border
      peer_connected:
        peer: dcgca.ulr.core
        peer_intf: Internal_Uplink01
      status: Connected
      subnet: 255.255.255.248
    - description: ''
      ip: 172.16.10.29
      mgt_only: false
      name: vif.internet
      subnet: 255.255.255.252
    - description: ''
      ip: 172.16.10.9
      mgt_only: false
      name: vif.uplink2cuca
      peer_connected:
        peer: CoreSPINEcuca01
        peer_intf: VL808
      status: Connected
      subnet: 255.255.255.252
    model: NSX-ESG
    role: edge-security-gateway
    site: CUCA
  groups:
  - edge-security-gateway
  - global
  hostname: 172.16.10.9
  password: admin2019
  platform: ios
  username: admin
dcgca.ulr.core:
  data:
    device_name: dcgca.ulr.core
    interfaces:
    - description: Uplink to ESG
      ip: 172.16.10.1
      mgt_only: false
      name: Internal_Uplink01
      peer_connected:
        peer: dcgca.esg.border
        peer_intf: vif.cuc.core2border
      status: Connected
      subnet: 255.255.255.248
    - description: Universal Logical Switch
      ip: 10.110.1.254
      mgt_only: false
      name: vif.gca.application
      subnet: 255.255.255.0
    - description: Universal Logical Switch
      ip: 10.110.2.30
      mgt_only: false
      name: vif.gca.database
      subnet: 255.255.255.224
    - description: Universal Logical Switch
      ip: 10.110.7.254
      mgt_only: false
      name: vif.gca.desktop
      subnet: 255.255.252.0
    - description: Universal Logical Switch
      ip: 10.110.2.62
      mgt_only: false
      name: vif.gca.fileshare
      subnet: 255.255.255.224
    - description: Universal Logical Switch
      ip: 10.110.2.158
      mgt_only: false
      name: vif.gca.monitoring
      subnet: 255.255.255.224
    - description: Universal Logical Switch
      ip: 10.110.2.126
      mgt_only: false
      name: vif.gca.security
      subnet: 255.255.255.192
    - description: Universal Logical Switch
      ip: 10.110.0.254
      mgt_only: false
      name: vif.gca.servers
      subnet: 255.255.255.0
    - description: Universal Logical Switch
      ip: 10.110.3.254
      mgt_only: false
      name: vif.gca.stage
      subnet: 255.255.255.128
    model: NSX-UDLR
    role: universal-dlr
    site: CUCA
  groups:
  - universal-dlr
  - global
  hostname: 172.16.10.1
  password: admin2019
  platform: ios
  username: admin
nsx-controller01:
  data:
    device_name: nsx-controller01
    interfaces:
    - description: ''
      ip: 10.104.2.33
      mgt_only: false
      name: e0
      subnet: 255.255.255.0
    model: NSX-Controller
    role: nsx-controller
    site: CUCA
  groups:
  - nsx-controller
  - global
  hostname: 10.104.2.31
  password: admin2019
  platform: ios
  username: admin
nsx-controller02:
  data:
    device_name: nsx-controller02
    interfaces:
    - description: ''
      ip: 10.104.2.33
      mgt_only: false
      name: e0
      subnet: 255.255.255.0
    model: NSX-Controller
    role: nsx-controller
    site: CUCA
  groups:
  - nsx-controller
  - global
  hostname: 10.104.2.32
  password: admin2019
  platform: ios
  username: admin
nsx-controller03:
  data:
    device_name: nsx-controller03
    interfaces:
    - description: ''
      ip: 10.104.2.33
      mgt_only: false
      name: e0
      subnet: 255.255.255.0
    model: NSX-Controller
    role: nsx-controller
    site: CUCA
  groups:
  - nsx-controller
  - global
  hostname: 10.104.2.33
  password: admin2019
  platform: ios
  username: admin
nsxmgt01:
  data:
    device_name: nsxmgt01
    interfaces:
    - description: Management
      ip: 10.104.2.33
      mgt_only: true
      name: e0
      subnet: 255.255.255.0
    model: NSX-Manager
    role: nsx-management
    site: CUCA
  groups:
  - nsx-management
  - global
  hostname: 10.104.2.27
  password: admin2019
  platform: ios
  username: admin

...